[package]
name = "cucumber_rust"
version = "0.7.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
description = "Cucumber testing framework for Rust. Fully native, no external test runners or dependencies."
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cucumber", "testing", "bdd", "atdd"]
repository = "https://github.com/bbqsrc/cucumber-rust"
documentation = "https://docs.rs/cucumber_rust"
homepage = "https://github.com/bbqsrc/cucumber-rust"
edition = "2018"

[dependencies]
# 0.8.1
gherkin = { package = "gherkin_rust", git = "https://github.com/BerhorShadowbuckle/gherkin-rust", branch = "allow_background_to_be_placed_in_rules" }

async-stream = "0.3.0"
async-trait = "0.1.40"
cute_custom_default = "2.1.0"
futures = "0.3.5"
globwalk = "0.8.0"
regex = "1.3.9"
shh = "1.0.1"
thiserror = "1.0.20"
termcolor = "1.1.0"
textwrap = { version = "0.12.1", features = ["terminal_size"] }
pathdiff = "0.2.0"

[[test]]
name = "cucumber_builder"
harness = false
